[tool.poetry]
name = "fabric"
version = "2.5.0"
description = ""
authors = ["Jeff Forcier <jeff@bitprophet.org>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
